pipeline:
  ping:
    image: tmaier/docker-compose:latest
    environment:
      DOCKER_HOST: unix:///drone/docker.sock
      SECRET_DJANGO_SECRET_KEY:
        from_secret: SECRET_DJANGO_SECRET_KEY
    volumes:
      - /etc/hosts:/etc/hosts
    secrets:
      - source: SSH_PRIVATE_KEY
        target: SSH_PRIVATE_KEY
    commands:
      - while (! docker info &>/dev/null); do sleep 1; done
      - python -m pip install --upgrade pip
      - pip install dump-env
      - dump-env -t ./backend/config/.env.template -p "SECRET_" > ./backend/config/.env
      - cat ./backend/config/.env
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml config
      - docker-compose run --rm web sh ./docker/ci.sh
      - "which ssh-agent || ( apk add --no-cache openssh-client )"
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh -o StrictHostKeyChecking=no ubuntu@app-skyexpo 'pwd'

services:
  docker:
    image: docker:dind
    privileged: true
    command: ["-H", "unix:///drone/docker.sock"]
