---

global-variables:
  image: &docker-compose-image tmaier/docker-compose:latest
  volumes: &docker-compose-volumes
    - name: hosts
      path: /etc/hosts
    - name: dockersock
      path: /var/run


kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
- name: create .env configuration file
  image: python:3.7.5-alpine3.10
  commands:
    - python -m pip install --upgrade pip
    - pip install dump-env
    - dump-env -t ./backend/config/.env.template -p 'SECRET_'
      --strict=SECRET_DJANGO_SECRET_KEY > ./backend/config/.env
  environment:
    SECRET_DJANGO_SECRET_KEY:
      from_secret: SECRET_DJANGO_SECRET_KEY
  when:
    branch:
      - develop
    event: {exclude: [pull_request]}


- name: prepare docker-compose
  image: *docker-compose-image
  volumes:
    *docker-compose-volumes
  commands:
    - while (! docker info &>/dev/null); do sleep 1; done
    - docker version
    - docker info
    - uname -a

- name: run backend CI
  image: *docker-compose-image
  volumes:
    *docker-compose-volumes
  pull: if-not-exists
  commands:
    - cp ./backend/config/.env.template ./backend/config/.env
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml config --quiet
    - docker-compose run --rm web sh ./docker/ci.sh

- name: deploy to staging
  image: *docker-compose-image
  volumes:
    *docker-compose-volumes
  pull: if-not-exists
  commands:
    - "which ssh-agent || ( apk add --no-cache openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no ubuntu@app-skyexpo 'pwd'
  when:
    branch:
      - develop
    event: {exclude: [pull_request]}

services:
  - name: docker
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
  - name: hosts
    host:
      path: /etc/hosts
