---

# This docker-compose file is required to bind ports in development,
# since binding ports in regular compose file will ruin scaling
# in production. Due to how `ports` directive is merged with two files.
#
# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker-compose up

version: "3.7"
services:
  web:
    ports:
      # We only bind ports directly in development:
      - "8000:8000"
      # shell_plus --notebook
      - "8888:8888"
    volumes:
      # We only mount source code in development:
      - ./backend:/code
    stdin_open: true
    tty: true

  web-app:
    build:
      dockerfile: dev.Dockerfile
    command: yarn start
    volumes:
      - ./web-app:/web-app
      - ./web-app/node_modules
    ports:
      - 3000:3000
