---

# This compose-file is production only. So, it should not be called directly.
#
# Instead, it should be a part of your deploy strategy.

version: "3.7"
services:
  nginx:
    build:
      context: ./backend
      dockerfile: ./docker/nginx/Dockerfile
    container_name: skyexpo-nginx
    restart: unless-stopped
    volumes:
      - django-static:/var/www/django/static:ro  # serving django's statics
      - django-media:/var/www/django/media:ro  # serving django's media
    depends_on:
      - web
      - web-app
    networks:
      - proxynet
    ports:
      - 80:80
      - 443:443

  web:
    <<: &web
      build:
        target: production_build
        context: ./backend
        dockerfile: ./docker/django/Dockerfile
        args:
          DJANGO_ENV: production
      restart: unless-stopped
      volumes:
        - django-media:/var/www/django/media  # since in dev it is app's folder
    command: sh ./docker/django/gunicorn.sh
    expose:
      - 8000
