# -*- coding: utf-8 -*-

# Generated by Django 2.2.7 on 2019-11-28 14:18

import django.contrib.postgres.fields
import django.core.validators
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('founding_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('logotype', models.ImageField(blank=True, upload_to='')),
                ('founder_email', models.EmailField(max_length=254, unique=True)),
                ('stage', models.CharField(choices=[('CONCEPT_STAGE', 'Concept stage'), ('GROWTH_STAGE', 'Growth stage (generating revenue)'), ('EARLY_STAGE', 'Early stage (market launch)'), ('SEED_STAGE', 'Seed stage (product development)')], max_length=33)),
                ('sectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AI_AND_ROBOTICS', 'AI and robotics'), ('IOT_AND_SENSORS', 'IoT and sensors'), ('AGRICULTURE', 'Agriculture')], max_length=15), size=None)),
                ('industries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BUSINESS_ANALYTICS', 'Business & Analytics'), ('FINANCIAL_SERVICES', 'Financial Services & Security'), ('ENTERTAINMENT', 'Entertainment and Mobile'), ('HEALTH_CARE', 'Health-care and Wellbeing'), ('E_COMMERCE', 'E-commerce, Adtech, Martech'), ('MATERIALS', 'Manufacturing and materials'), ('HARDWARE', 'Hardware & Iot'), ('MOBILITY', 'Mobility & Transportation'), ('ENERGY', 'Energy and Cleantech')], max_length=29), size=None)),
                ('product_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('OTHER', 'Other')], max_length=8), size=None)),
                ('min_investment_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_investment_size', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
