---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: no-commit-to-branch
        args: [--branch, master, --branch, develop]
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: docker-compose -f backend/docker-compose.yml -f backend/docker-compose.override.yml run --rm web flake8
        pass_filenames: false
        language: system
