targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - lib/main.dart

        options:
          formatted: true
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          nullable: true
