name: mobile
description: Skyexpo.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  equatable: ^1.1.1
  flutter_dotenv: ^2.1.0
  flutter:
    sdk: flutter
  flutter_flipperkit: ^0.0.21
  flipperkit_http_interceptor: ^0.0.1
  flutter_redux: ^0.6.0
  http: ^0.12.0+4
  image_picker: ^0.6.4
  json_annotation: ^3.0.1
  percent_indicator: "^2.1.1"
  redux: ^4.0.0
  redux_epics: ^0.13.0
  redux_remote_devtools: ^1.0.2
  reselect: ^0.4.0
  vnum: ^1.2.4

dev_dependencies:
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  mockito: ^4.1.1
  reflectable: ^2.0.10+1
flutter:
  assets:
    - .env
  uses-material-design: true
