---

log:
  level: "DEBUG"

entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"

ping:
  entryPoint: "web"

providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"

#certificatesResolvers:
#  letsencrypt:
#    acme:
#      email: "marcin.josinski@skygate.io"
#      storage: "acme.json"
#      httpChallenge:
#        entryPoint: "web"
