# Generated by Django 2.2.12 on 2020-04-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20200309_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angelinvestor',
            old_name='avatar',
            new_name='logotype',
        ),
    ]
