export const startupInitialValues = {
    startupName: '',
    website: '',
    phone: '',
    startupContact: '',
    country: '',
    foundingDate: '',
    shortDescription: '',
    logo: '',
    teamMembers: [
        {
            name0: '',
            email0: '',
        },
    ],
    industries: [''],
    sectors: [''],
    investmentStage: [''],
    companyStage: [''],
    productType: [''],
    productOnMarket: '',
    targetMarket: [''],
    businessType: [''],
    minimumInvest: '',
    maximumInvest: '',
};

export const companyInvestorInitialValues = {
    companyName: '',
    website: '',
    phone: '',
    companyContact: '',
    country: '',
    foundingDate: '',
    shortDescription: '',
    logo: '',
    teamMembers: [
        {
            name0: '',
            email0: '',
        },
    ],
    industries: [''],
    sectors: [''],
    investmentStage: [''],
    companyStage: [''],
    productType: [''],
    productOnMarket: '',
    targetMarket: [''],
    businessType: [''],
    minimumInvest: '',
    maximumInvest: '',
};

export const individualInvestorInitialValues = {
    fullName: '',
    website: '',
    phone: '',
    individualContact: '',
    country: '',
    foundingDate: '',
    shortDescription: '',
    logo: '',
    teamMembers: [
        {
            name0: '',
            email0: '',
        },
    ],
    industries: [''],
    sectors: [''],
    investmentStage: [''],
    companyStage: [''],
    productType: [''],
    productOnMarket: '',
    targetMarket: [''],
    businessType: [''],
    minimumInvest: '',
    maximumInvest: '',
};
