export const startupInitialValues = {
    name: '',
    website: '',
    phoneNumber: '',
    email: '',
    country: '',
    foundingDate: '',
    description: '',
    logotype: '',
    teamMembers: [
        {
            name: '',
            email: '',
        },
    ],
    industries: [''],
    sectors: [''],
    investmentStage: [''],
    companyStage: [''],
    productType: [''],
    productOnMarket: '',
    targetMarket: [''],
    businessType: [''],
    minimumInvest: '',
    maximumInvest: '',
};

export const companyInvestorInitialValues = {
    name: '',
    website: '',
    phoneNumber: '',
    email: '',
    country: '',
    foundingDate: '',
    description: '',
    logotype: '',
    teamMembers: [
        {
            name: '',
            email: '',
        },
    ],
    industries: [''],
    sectors: [''],
    investmentStage: [''],
    companyStage: [''],
    productType: [''],
    productOnMarket: '',
    targetMarket: [''],
    businessType: [''],
    minimumInvest: '',
    maximumInvest: '',
};

export const individualInvestorInitialValues = {
    name: '',
    website: '',
    phoneNumber: '',
    email: '',
    country: '',
    foundingDate: '',
    description: '',
    logotype: '',
    industries: [''],
    sectors: [''],
    investmentStage: [''],
    companyStage: [''],
    productType: [''],
    productOnMarket: '',
    targetMarket: [''],
    businessType: [''],
    minimumInvest: '',
    maximumInvest: '',
};
